version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always
    networks:
      - backend_network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - backend_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    networks:
      - backend_network
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend_network
    depends_on:
      - redis
      - kafka
    ports:
      - "8000:8000"
    
networks:
  backend_network:
    driver: bridge
